### ISSUE TITLE
Locking repo exclusive failed: Resource temporarily unavailable

### ISSUE THREAD

**Issue by agners** [advancedtelematic/meta-updater#412] opened 2018-10-26 13:22 UTC
We try to store two (similar) images into the same OSTree repository. The thought is that we could switch between the two using OSTree (which works surprisingly well). On our CI infrastructure however it seems that this can cause race conditions when two independent `bitbake` instances use the same `OSTREE_REPO`. Maybe the `do_image_ostree` needs some higher level locking mechanism which makes sure the task gets exclusive access to the OSTree repo?

```
ERROR: torizon-core-docker-0.2.26-r0 do_image_ostree: Function failed: do_image_ostree (log file is located at /workdir/oe/tmp/work/colibri_imx7-torizon-linux-gnueabi/torizon-core-docker/0.2.26-r0/temp/log.do_image_ostree.1720)
ERROR: Logfile of failure stored in: /workdir/oe/tmp/work/colibri_imx7-torizon-linux-gnueabi/torizon-core-docker/0.2.26-r0/temp/log.do_image_ostree.1720
Log data follows:
| DEBUG: Executing python function set_image_size
| DEBUG: 844146.000000 = 367020 * 2.300000
| DEBUG: 844146.000000 = max(844146.000000, 65536)[844146.000000] + 2
| DEBUG: 844146.000000 = int(844146.000000)
| DEBUG: 844146 = aligned(844146)
| DEBUG: returning 844146
| DEBUG: Python function set_image_size finished
| DEBUG: Executing python function extend_recipe_sysroot
| NOTE: Direct dependencies are ['/workdir/oe/build/conf/../../layers/openembedded-core/meta/recipes-core/glibc/ldconfig-native_2.12.1.bb:do_populate_sysroot', '/workdir/oe/build/conf/../../layers/meta-toradex-torizon/recipes-kernel/linux/linux-stable_git.bb:do_populate_sysroot', '/workdir/oe/build/conf/../../layers/openembedded-core/meta/recipes-devtools/quilt/quilt-native_0.65.bb:do_populate_sysroot', 'virtual:native:/workdir/oe/build/conf/../../layers/meta-updater/recipes-sota/ostree/ostree_git.bb:do_populate_sysroot', '/workdir/oe/build/conf/../../layers/openembedded-core/meta/recipes-core/glibc/cross-localedef-native_2.28.bb:do_populate_sysroot', 'virtual:native:/workdir/oe/build/conf/../../layers/openembedded-core/meta/recipes-support/lzop/lzop_1.03.bb:do_populate_sysroot', 'virtual:native:/workdir/oe/build/conf/../../layers/openembedded-core/meta/recipes-connectivity/openssl/openssl_1.1.1.bb:do_populate_sysroot', '/workdir/oe/build/conf/../../layers/openembedded-core/meta/recipes-kernel/kmod/kmod-native_git.bb:do_populate_sysroot', 'virtual:native:/workdir/oe/build/conf/../../layers/openembedded-core/meta/recipes-extended/xz/xz_5.2.4.bb:do_populate_sysroot', '/workdir/oe/build/conf/../../layers/openembedded-core/meta/recipes-kernel/kern-tools/kern-tools-native_git.bb:do_populate_sysroot', 'virtual:native:/workdir/oe/build/conf/../../layers/openembedded-core/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot', '/workdir/oe/build/conf/../../layers/openembedded-core/meta/recipes-devtools/binutils/binutils-cross_2.31.bb:do_populate_sysroot', 'virtual:native:/workdir/oe/build/conf/../../layers/openembedded-core/meta/recipes-extended/pigz/pigz_2.4.bb:do_populate_sysroot', 'virtual:native:/workdir/oe/build/conf/../../layers/openembedded-core/meta/recipes-extended/unzip/unzip_6.0.bb:do_populate_sysroot', '/workdir/oe/build/conf/../../layers/openembedded-core/meta/recipes-devtools/gcc/gcc-cross_8.2.bb:do_populate_sysroot', '/workdir/oe/build/conf/../../layers/openembedded-core/meta/recipes-devtools/qemu/qemuwrapper-cross_1.0.bb:do_populate_sysroot', 'virtual:native:/workdir/oe/build/conf/../../layers/openembedded-core/meta/recipes-kernel/dtc/dtc_1.4.7.bb:do_populate_sysroot', 'virtual:native:/workdir/oe/build/conf/../../layers/openembedded-core/meta/recipes-core/coreutils/coreutils_8.30.bb:do_populate_sysroot', 'virtual:native:/workdir/oe/build/conf/../../layers/openembedded-core/meta/recipes-devtools/makedevs/makedevs_1.0.1.bb:do_populate_sysroot', 'virtual:native:/workdir/oe/build/conf/../../layers/openembedded-core/meta/recipes-core/util-linux/util-linux_2.32.1.bb:do_populate_sysroot', 'virtual:native:/workdir/oe/build/conf/../../layers/openembedded-core/meta/recipes-devtools/bison/bison_3.0.4.bb:do_populate_sysroot', 'virtual:native:/workdir/oe/build/conf/../../layers/openembedded-core/meta/recipes-core/update-rc.d/update-rc.d_0.8.bb:do_populate_sysroot', 'virtual:native:/workdir/oe/build/conf/../../layers/openembedded-core/meta/recipes-extended/bc/bc_1.07.1.bb:do_populate_sysroot', '/workdir/oe/build/conf/../../layers/openembedded-core/meta/recipes-kernel/kmod/depmodwrapper-cross_1.0.bb:do_populate_sysroot', 'virtual:native:/workdir/oe/build/conf/../../layers/openembedded-core/meta/recipes-devtools/opkg-utils/opkg-utils_0.3.6.bb:do_populate_sysroot', 'virtual:native:/workdir/oe/build/conf/../../layers/openembedded-core/meta/recipes-devtools/opkg/opkg_0.3.6.bb:do_populate_sysroot']
| NOTE: Installed into sysroot: ['linux-stable', 'ostree-native', 'lzop-native', 'kern-tools-native', 'binutils-cross-arm', 'unzip-native', 'gcc-cross-arm', 'coreutils-native', 'bison-native', 'bc-native', 'gobject-introspection-native', 'fuse-native', 'gpgme-native', 'libcap-native', 'dosfstools-native', 'mtools-native', 'u-boot-script-toradex', 'parted-native', 'mpfr-native', 'libmpc-native', 'gmp-native', 'linux-libc-headers', 'glibc', 'libassuan-native', 'libgpg-error-native', 'swig-native', 'gperf-native', 'gcc-runtime', 'libgcc']
| NOTE: Skipping as already exists in sysroot: ['ldconfig-native', 'quilt-native', 'cross-localedef-native', 'openssl-native', 'kmod-native', 'xz-native', 'pseudo-native', 'pigz-native', 'qemuwrapper-cross', 'dtc-native', 'makedevs-native', 'util-linux-native', 'update-rc.d-native', 'depmodwrapper-cross', 'opkg-utils-native', 'opkg-native', 'systemd-systemctl-native', 'gnu-config-native', 'libarchive-native', 'curl-native', 'glib-2.0-native', 'pkgconfig-native', 'python3-native', 'automake-native', 'autoconf-native', 'libtool-native', 'attr-native', 'e2fsprogs-native', 'shadow-native', 'lzo-native', 'zlib-native', 'gtk-doc-native', 'gettext-minimal-native', 'flex-native', 'texinfo-dummy-native', 'qemu-native', 'nss-native', 'debianutils-native', 'ncurses-native', 'readline-native', 'libsolv-native', 'libffi-native', 'bzip2-native', 'gettext-native', 'libpcre-native', 'sqlite3-native', 'gdbm-native', 'm4-native', 'alsa-lib-native', 'pixman-native', 'libusb1-native', 'nspr-native', 'ninja-native', 'cmake-native', 'rpm-native', 'expat-native', 'libpng-native', 'util-macros-native', 're2c-native', 'db-native', 'dbus-native', 'elfutils-native', 'file-native', 'popt-native']
| DEBUG: sed -e 's:^[^/]*/:/workdir/oe/tmp/work/colibri_imx7-torizon-linux-gnueabi/torizon-core-docker/0.2.26-r0/recipe-sysroot-native/:g' /workdir/oe/tmp/sysroots-components/x86_64/gcc-cross-arm/fixmepath /workdir/oe/tmp/sysroots-components/x86_64/bison-native/fixmepath /workdir/oe/tmp/sysroots-components/x86_64/gobject-introspection-native/fixmepath /workdir/oe/tmp/sysroots-components/x86_64/gpgme-native/fixmepath /workdir/oe/tmp/sysroots-components/x86_64/gmp-native/fixmepath /workdir/oe/tmp/sysroots-components/x86_64/libassuan-native/fixmepath /workdir/oe/tmp/sysroots-components/x86_64/libgpg-error-native/fixmepath | xargs sed -i -e 's:FIXMESTAGINGDIRTARGET:/workdir/oe/tmp/work/colibri_imx7-torizon-linux-gnueabi/torizon-core-docker/0.2.26-r0/recipe-sysroot:g; s:FIXMESTAGINGDIRHOST:/workdir/oe/tmp/work/colibri_imx7-torizon-linux-gnueabi/torizon-core-docker/0.2.26-r0/recipe-sysroot-native:g' -e 's:FIXME_COMPONENTS_DIR:/workdir/oe/tmp/sysroots-components:g' -e 's:FIXME_HOSTTOOLS_DIR:/workdir/oe/tmp/hosttools:g' -e 's:FIXME_PKGDATA_DIR:/workdir/oe/tmp/pkgdata/colibri-imx7:g' -e 's:FIXME_PSEUDO_LOCALSTATEDIR:/workdir/oe/tmp/work/colibri_imx7-torizon-linux-gnueabi/torizon-core-docker/0.2.26-r0/pseudo/:g' -e 's:FIXME_LOGFIFO:/workdir/oe/tmp/work/colibri_imx7-torizon-linux-gnueabi/torizon-core-docker/0.2.26-r0/temp/fifo.1720:g'
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing shell function do_image_ostree
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| 469198ac3736b9a00eb64c8b0f300b892244a705941a695c84b8a7f089408d86
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| unknown fcntl argument 37, assuming long argument.
| error: Locking repo exclusive failed: Resource temporarily unavailable
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_image_ostree (log file is located at /workdir/oe/tmp/work/colibri_imx7-torizon-linux-gnueabi/torizon-core-docker/0.2.26-r0/temp/log.do_image_ostree.1720)
NOTE: recipe torizon-core-docker-0.2.26-r0: task do_image_ostree: Failed
ERROR: Task (/workdir/oe/build/conf/../../layers/meta-toradex-torizon/recipes-images/images/torizon-core-docker.bb:do_image_ostree) failed with exit code '1'
NOTE: Tasks Summary: Attempted 5476 tasks of which 4306 didn't need to be rerun and 1 failed.
NOTE: Writing buildhistory

Summary: 1 task failed:
  /workdir/oe/build/conf/../../layers/meta-toradex-torizon/recipes-images/images/torizon-core-docker.bb:do_image_ostree
Summary: There were 38 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
```

**Comment by patrickvacek** [comment] 2018-10-26 13:55
@agners Interesting problem. That's not something that we normally do, so we haven't put much thought into this. It looks like ostree has internal locking mechanisms, but I can't find anything about external locking in the docs. I haven't checked the code thoroughly, though, so it's possible that there is something available. Otherwise, this would probably require some custom work, either in ostree itself or wrapped around our call to `ostree commit`.

**Comment by agners** [comment] 2018-10-26 14:00
@patrickvacek yeah we just bumped into that today, we are aware that this is probably not something people usually do. I thought I still create an issue so it is properly tracked.

I guess from a OSTree perspecitive everything works as expected: It is in use, so you should not use it... Its just that this is not useful behavior for the upper layer (bitbake).

In other places `bitbake` uses `bb.utils.lockfile` to lock resources which potentially are in use by multiple different bitbake processes (e.g. `DL_DIR`). And afaik, this blocks until the lock is available. I guess we could do the same thing in `do_image_ostree`. We probably try that sometime in the next few days.

**Comment by patrickvacek** [comment] 2018-10-26 14:04
> I thought I still create an issue so it is properly tracked.

Yes, of course, thanks for bringing it to our attention!

> In other places `bitbake` uses `bb.utils.lockfile` to lock resources which potentially are in use by multiple different bitbake processes (e.g. `DL_DIR`). And afaik, this blocks until the lock is available. I guess we could do the same thing in `do_image_ostree`. We probably try that sometime in the next few days.

Great, please let us know if you have success with that method. That seems like a reasonable way to try to address the problem.

**Comment by agners** [comment] 2018-11-01 22:28
We did found a solution:
https://www.mail-archive.com/openembedded-core@lists.openembedded.org/msg116423.html

Will send a pull request.

**Comment by patrickvacek** [comment] 2018-11-02 16:17
Fixed by #421 .

**Comment by agners** [comment] 2019-01-14 16:56
Unfortunately we saw this again even with the lockfiles in place. Can we reopen the issue? Will investigate further.

As far as I understand the output the `ostree commit` actually succeeds (the hash in the output is prove of that), but the subsequent `ostree summary -u` fails. The `unknown fcntl argument` messages come from OpenEmbedded/pseudo, but should not be harmful. It shows however that locking on the second ostree commands times out after 30 attempts (which is the ostree default timeout when using locking).

**Comment by patrickvacek** [comment] 2019-01-15 08:33
@agners Sure, we can reopen it. That's unfortunate that you're seeing it again. It doesn't make sense according to my current understanding, so we're either doing something wrong or I don't actually understand it. It's not particularly easy for me to reproduce this; is this something you can look into further at present?

**Comment by patrickvacek** [comment] 2019-01-15 08:34
Oh, and what's the error log? Is it basically the same as the original problem?

**Comment by agners** [comment] 2019-01-15 09:02
Yes, very same log as the original problem.

It is really puzzling, because the `lockfiles` really should mutually exclude the parallel builds...

**Comment by dbalashenka** [comment] 2019-10-22 12:49
We had similar error message in logs on yocto sumo. This patch seems to be fixing it: https://patchwork.openembedded.org/patch/157909/

**Comment by agners** [comment] 2020-04-29 08:37
@dbalashenka note that the `unknown fcntl argument 37, assuming long argument.` are really not the problem here. It is the `error: Locking repo exclusive failed: Resource temporarily unavailable`  which is concerning.

@patrickvacek I haven't seen this issue in a long time in our infrastructure. And that despite us building nightly with pretty much the same concurrency setting. But I think we also "tuned" NFS a bit, because there were indications that the lockfile mechanism might fail if the OSTree is on a NFS. So it might be really an infrastructure issue on our end which still triggered it. From my side I am fine closing this issue. It really seems we do the right thing here and this is not a meta-updater issue. In case it reappears and we have indication its a meta-updater problem we still can reopen.

**Comment by patrickvacek** [comment] 2020-04-29 09:08
Closing since it sounds like the problem hasn't been observed in a while, and we haven't been able to reproduce it. We can reopen if necessary.

**Closed by patrickvacek** 2020-04-29 09:08 UTC
